### ISSUE TITLE
No longer valid protein id.

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-frontend#151]
Description

Q12964

G62765YT - glygen id but no longer valid dont change the sentence same for protein. so with history no change.

Use below text,

Protein: G3V9U9, Q9Z2Y4, Q4V8N1, Q6IRJ6

Glycan: G00318GT, G01410DC, G01797UE, G02351CQ

UniProt accession xxx does not exist in GlyGen.

GlyTouCan acession xxx does not exist in GlyGen.

with history, earlier valid

G3V9U9 is no longer a valid UniProt accession in GlyGen.

G3V9U9 is no longer a valid GlyTouCan accession in GlyGen.

 

merged example: 

accession       replacewith

G00318GT        G63349UI

**Comment by jeet-vora** [comment]
Some comments and info from Robel

G00104PH (Valid GTC but not part of GlyGen ….  , we can discuss this and other protein ac in meeting)

G00318GT (obsolete glytoucan accession and has been replaced by G63349UI)
Fixed on tst

<img width="518" alt="image" src="https://user-images.githubusercontent.com/25825266/207692896-02a060e0-c8e3-4847-8ce3-5942f5cec32e.png">


G3V9U9 (obsolete uniprot accession, has been merged into Q63175)
Fixed on tst

<img width="628" alt="image" src="https://user-images.githubusercontent.com/25825266/207692986-8f889d29-b67c-4978-88ee-1e685d1a5c73.png">


P25623 (uniprot ac for yeast not part of GlyGen but is a valid ac)
This is not a good example because it is not in the downloaded accession-history-* files

**Comment by ReneRanzinger** [comment]
@jeet-vora We will have to contact Uniprot and retrieve the history two column file for ALL uniprot IDs from them.

**Comment by sujeetvkulkarni** [comment]
related ticket,
https://github.com/glygener/glygen-frontend/issues/44

**Comment by sujeetvkulkarni** [comment]
730ff2e2312f6d850c73b9870d359691b46c570a
