### ISSUE TITLE
API schema documentation: Glycan details

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-frontend#99]
@rykahsay will auto-generate a schema from the API. @kmartinez834 will add required properties and description afterwards.

**Comment by kmartinez834** [comment]
glygen-backend-api/specs/glycan/detail/response.schema.json has been updated with minimum requirements for glycan detail API.

There were 35 records that failed due to the following missing values:

- "gene_name" for P27958-1 (Genome polyprotein, Hepatitis C virus (isolate H))
- "gene_name" for P20762-1 (Ig gamma-2C chain C region, Rattus norvegicus)
- "gene_name" for Q6ZSR9-1 (Uncharacterized protein FLJ45252, Homo sapiens)
- "common_name" for tax ID 11103 (Hepacivirus C)
- "composition" and "composition_expanded" for G53621MK and G82740LG 

Tasks for @ReneRanzinger and @sujeetvkulkarni :

- Clone the glygen-backend-api repository in tst and run `python3 run_api_test.py -m 2 -g glycan`
- Review the missing values above and let me know if we should resolve the issues, or relax the schema requirements

**Comment by kmartinez834** [comment]
@jeet-vora can you take a look at the missing gene names above?

**Comment by jeet-vora** [comment]
@kmartinez834 
"gene_name" for P27958-1 (Genome polyprotein, Hepatitis C virus (isolate H)) -> No gene name in the source file
"gene_name" for P20762-1 (Ig gamma-2C chain C region, Rattus norvegicus) -> No gene name in the source file
"gene_name" for Q6ZSR9-1 (Uncharacterized protein FLJ45252, Homo sapiens) -> No gene name in the source file

"common_name" for tax ID 11103 (Hepacivirus C) -> There is no common name in species_info.csv because it is at the species level we have data at isolate level. We can add HCV or Hepatitis C virus as common name in the file. On the front end HCV is used as common name.

**Comment by kmartinez834** [comment]
- Relaxed glycan schema to allow missing "gene_name"
- Added common name "HCV" to tax ID 11103 to species_info.csv
- Created ticket https://github.com/glygener/glygen-issues/issues/101 to discuss missing compositions
